# Generated by Django 3.2.5 on 2021-07-11 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0004_categoria_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatecno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('asunto', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
        migrations.AddField(
            model_name='categoria',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ranking',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
