# Generated by Django 3.2.1 on 2021-06-21 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='images/default.png', upload_to='perfiles/')),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_cumpleaños', models.DateField()),
                ('genero', models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=40, verbose_name='Gender')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
